package krustykrabinventorysystem;

import java.awt.*;
import javax.swing.*;
import java.io.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;


public class MainForm extends javax.swing.JFrame    {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        addTableHeader();
        setLocationRelativeTo(null);
        setPreEnteredData();
        
        //drop shadow
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        lblMenuLogo = new javax.swing.JLabel();
        pnlMainCardLayout = new javax.swing.JPanel();
        pnlReports = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlInventoryEntryForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPictureHolder = new javax.swing.JLabel();
        btnChooseFile = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        pnlInventoryListForm = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        btnAddItem = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnMinimize = new javax.swing.JButton();
        pnlBG = new javax.swing.JPanel();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnExit.setText("jButton6");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        pnlMenu.setBackground(new java.awt.Color(98, 0, 238));
        pnlMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlMenuMouseDragged(evt);
            }
        });
        pnlMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlMenuMousePressed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(98, 0, 238));
        btnHome.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setHorizontalAlignment(SwingConstants.LEFT);
        btnHome.setBorder(null);
        btnHome.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnInventory.setBackground(new java.awt.Color(98, 0, 238));
        btnInventory.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setText("Inventory");
        btnInventory.setBorder(null);
        btnInventory.setPreferredSize(new java.awt.Dimension(43, 18));
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(98, 0, 238));
        btnReports.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("Reports");
        btnReports.setBorder(null);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnSettings.setText("jButton1");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnInventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblMenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblMenuLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSettings)
                .addContainerGap())
        );

        pnlMainCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainCardLayout.setLayout(new java.awt.CardLayout());

        pnlReports.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlReportsLayout = new javax.swing.GroupLayout(pnlReports);
        pnlReports.setLayout(pnlReportsLayout);
        pnlReportsLayout.setHorizontalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        pnlReportsLayout.setVerticalGroup(
            pnlReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        pnlMainCardLayout.add(pnlReports, "card2");

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        pnlMainCardLayout.add(pnlHome, "card2");

        pnlInventoryEntryForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Inventory Entry");

        jLabel3.setText("Code:");

        jLabel4.setText("Name:");

        jLabel5.setText("Description:");

        jLabel6.setText("Amount:");

        jLabel7.setText("Quantity:");

        jLabel8.setText("Picture:");

        btnChooseFile.setText("Choose file...");
        btnChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFileActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodeKeyTyped(evt);
            }
        });

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });

        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAmountKeyTyped(evt);
            }
        });

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
        });

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        javax.swing.GroupLayout pnlInventoryEntryFormLayout = new javax.swing.GroupLayout(pnlInventoryEntryForm);
        pnlInventoryEntryForm.setLayout(pnlInventoryEntryFormLayout);
        pnlInventoryEntryFormLayout.setHorizontalGroup(
            pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                                .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(14, 14, 14)
                                        .addComponent(txtName))
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                                        .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInventoryEntryFormLayout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18))
                                            .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(15, 15, 15)))
                                        .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 58, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChooseFile)
                    .addComponent(lblPictureHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInventoryEntryFormLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
        pnlInventoryEntryFormLayout.setVerticalGroup(
            pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                        .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlInventoryEntryFormLayout.createSequentialGroup()
                        .addComponent(lblPictureHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChooseFile)
                        .addGap(18, 37, Short.MAX_VALUE)))
                .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(pnlInventoryEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnReset)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pnlMainCardLayout.add(pnlInventoryEntryForm, "card2");

        pnlInventoryListForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Inventory List");

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Edit", "Delete", "Image", "Code", "Name", "Description", "Amount", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventory.setEditingRow(0);
        tblInventory.setFillsViewportHeight(true);
        tblInventory.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblInventory.setShowHorizontalLines(false);
        tblInventory.setShowVerticalLines(false);
        tblInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblInventoryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblInventoryMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblInventory);

        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Item");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Item");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlInventoryListFormLayout = new javax.swing.GroupLayout(pnlInventoryListForm);
        pnlInventoryListForm.setLayout(pnlInventoryListFormLayout);
        pnlInventoryListFormLayout.setHorizontalGroup(
            pnlInventoryListFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInventoryListFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventoryListFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlInventoryListFormLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventoryListFormLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addGroup(pnlInventoryListFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInventoryListFormLayout.createSequentialGroup()
                                .addComponent(btnAddItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        pnlInventoryListFormLayout.setVerticalGroup(
            pnlInventoryListFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryListFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInventoryListFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInventoryListFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(15, 15, 15))
        );

        pnlMainCardLayout.add(pnlInventoryListForm, "card2");

        btnMinimize.setText("jButton6");
        btnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizeActionPerformed(evt);
            }
        });

        pnlBG.setBackground(new java.awt.Color(255, 255, 255));
        pnlBG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlBGMouseDragged(evt);
            }
        });
        pnlBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBGMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlBGLayout = new javax.swing.GroupLayout(pnlBG);
        pnlBG.setLayout(pnlBGLayout);
        pnlBGLayout.setHorizontalGroup(
            pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        pnlBGLayout.setVerticalGroup(
            pnlBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMainCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnMinimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMainCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("myFrame");
        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void close()
    {
        pnlHome.setVisible(false);
        pnlInventoryEntryForm.setVisible(false);
        pnlInventoryListForm.setVisible(false);
        pnlReports.setVisible(false);
        
    }
    
    void setPreEnteredData()
    {
        JLabel imageLabel = newImage("C:\\Users\\Victorio\\Documents\\NetBeansProjects\\KrustyKrabInventorySystem\\src\\images\\bread.jpg");
        code = "111453";
        name = "Buns";
        descri = "6inches diameter, w/ sesame seeds, imported from atlantis";
        amt = "25.00";
        qty = "350";
        model.addRow(new Object[]{imageLabel,code, name, descri, amt, qty});
        
        imageLabel = newImage("C:\\Users\\Victorio\\Documents\\NetBeansProjects\\KrustyKrabInventorySystem\\src\\images\\cheese.png");
        code = "111421";
        name = "Cheese";
        descri = "3x3inches,pure dairy, imported from atlantis";
        amt = "70.00";
        qty = "140";
        model.addRow(new Object[]{imageLabel,code, name, descri, amt, qty});
        
        imageLabel = newImage("C:\\Users\\Victorio\\Documents\\NetBeansProjects\\KrustyKrabInventorySystem\\src\\images\\flour.png");
        code = "111485";
        name = "Flour";
        descri = "50kg,pure flour,all natural,imported from spratlys islands";
        amt = "900.00";
        qty = "19";
        model.addRow(new Object[]{imageLabel,code, name, descri, amt, qty});
        
        imageLabel = newImage("C:\\Users\\Victorio\\Documents\\NetBeansProjects\\KrustyKrabInventorySystem\\src\\images\\ketchup.png");
        code = "113451";
        name = "ketchup";
        descri = "1Liter,made with natural tomatoes, imported from new zealand";
        amt = "60.00";
        qty = "15";
        model.addRow(new Object[]{imageLabel,code, name, descri, amt, qty});
    }
    
     
    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        close();
        pnlHome.setVisible(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
            // TODO add your handling code here:
        close();
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        pnlInventoryListForm.setVisible(true);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        close();
        pnlInventoryEntryForm.setVisible(true);
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        close();
        pnlReports.setVisible(true);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        String Exit[]={"Yes","No"};
        int pili= JOptionPane.showOptionDialog(null,"Are you sure you want to exit?", "EXIT", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE,null, Exit, Exit[1]);
        if(pili==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizeActionPerformed
        setState(ICONIFIED);
    }//GEN-LAST:event_btnMinimizeActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
        clearFields();
        pnlInventoryListForm.setVisible(true);
        isInEditMode = false;
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearFields();
    }//GEN-LAST:event_btnResetActionPerformed

    
    
    public void removeSelectedRows(JTable table)
    {
        DefaultTableModel model = (DefaultTableModel) this.tblInventory.getModel();
        int[] rows = table.getSelectedRows();
        for(int i=0;i<rows.length;i++){
        model.removeRow(rows[i]-i);
   }
}
    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed
        
       // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser("C:\\Users\\Victorio\\Documents\\NetBeansProjects\\KrustyKrabInventorySystem\\src\\images");
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.setFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
 
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            ImageIcon ii = new ImageIcon(selectedImagePath);
//            Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblPictureHolder.getWidth(), lblPictureHolder.getHeight(), Image.SCALE_SMOOTH);
 
            lblPictureHolder.setIcon(new ImageIcon(image));
        
        }
    }//GEN-LAST:event_btnChooseFileActionPerformed
    //PUBLIC DECLARE
    DefaultTableModel model;
    public String code = "";
    public String name = "";
    public String descri = "";
    public String amt = "";
    public String qty = "";
    boolean isInEditMode = false;
    String selectedImagePath = "";
    
    int locatedRow;
    int locatedCol;
    
    int mousePX;
    int mousePY;
    
   public void addTableHeader() {
       
       ImageIcon ii = new ImageIcon("C:\\Users\\Victorio\\Documents\\NetBeansProjects\\KrustyKrabInventorySystem\\src\\kkrab.png");
       Image image = ii.getImage().getScaledInstance(lblMenuLogo.getWidth(), lblMenuLogo.getHeight(), Image.SCALE_SMOOTH);
 
            lblMenuLogo.setIcon(new ImageIcon(image));
       
        model = (DefaultTableModel) tblInventory.getModel();
        Object[] newIdentifiers = new Object[]{ "Image", "Code", "Name", "Description", "Amount", "Quantity"};
        model.setColumnIdentifiers(newIdentifiers);
        tblInventory.setFillsViewportHeight(true);
        tblInventory.getColumn("Image").setCellRenderer(new CellRenderer());
        tblInventory.setShowGrid(false);
        UIDefaults defaults = UIManager.getLookAndFeelDefaults();
if (defaults.get("Table.alternateRowColor") == null)
    defaults.put("Table.alternateRowColor", new Color(240, 240, 240));
TableColorCellRenderer renderer = new TableColorCellRenderer();
       
       tblInventory.setDefaultRenderer(Object.class, renderer);

tblInventory.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        
            
    }
});
    }
   class CellRenderer implements TableCellRenderer {
 
        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
 
            TableColumn tb = tblInventory.getColumn("Image");
            tb.setMaxWidth(60);
            tb.setMinWidth(60);
 
            tblInventory.setRowHeight(60);
 
            return (Component) value;
        }
 
    }
   
   
 public class TableColorCellRenderer implements TableCellRenderer {
    private final TableCellRenderer RENDERER = new DefaultTableCellRenderer();
    @Override
    public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
        Component c = RENDERER.getTableCellRendererComponent(jtable, o, bln, bln1, i, i1);
        
        
       if(i1 == 5)
       {
           Object res = jtable.getModel().getValueAt(i, i1);
           int aver = Integer.parseInt(res.toString());
        Color color = null;
         if(!(aver <= 20))
                    {
                        color = Color.BLACK;
                        c.setForeground(color);
                        
                    }
         else
         {
             color = Color.RED;
             c.setForeground(color);
         }
         
       }
       else 
       {
           c.setForeground(Color.BLACK);
       }
       
       
        return c;
    }
    
}
 
    public JLabel newImage(String imagePath)
    {
        JLabel imageLabel = new JLabel();
        ImageIcon imageicon = new ImageIcon(imagePath);
        Image img = imageicon.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        imageLabel.setIcon(new ImageIcon(img));
        return imageLabel;
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        
        code = txtCode.getText();
        name = txtName.getText();
        descri = txtDescription.getText();
        amt = txtAmount.getText();
        qty = txtQuantity.getText();
 
        JLabel imageLabel = newImage(selectedImagePath);
//        imageLabel.setIcon(imageicon);
 
try
{
        //Checking if one or more field is empty
        if(!(txtCode.getText().isEmpty() || txtName.getText().isEmpty() || txtDescription.getText().isEmpty() || txtAmount.getText().isEmpty() || txtQuantity.getText().isEmpty() || lblPictureHolder.getIcon().equals(null) ))
        {
            int tblRowCount = tblInventory.getModel().getRowCount();
            boolean isCodeExisting = false;
            for(int x = 1; x <= tblRowCount; x++)
            {
                String codeFromTbl = tblInventory.getModel().getValueAt(tblRowCount-x,1).toString();
                
                if((codeFromTbl.equals(txtCode.getText())) && !(codeFromTbl.equals(model.getValueAt(locatedRow,1))))
                {
                    JOptionPane.showMessageDialog(null, "You have entered an existing ITEM CODE");
                    isCodeExisting = true;
                    break;
                }
            }
            
            
            if(isCodeExisting == false)
            {
                if(isInEditMode == false)
                {
                        model.addRow(new Object[]{imageLabel,code, name, descri, amt, qty});
                        JOptionPane.showMessageDialog(null, "Data Inserted");
                        
                        //clear fields after inserting the data
                        clearFields();
                        close();
                        pnlInventoryListForm.setVisible(true);
                       
                }
                else
                {
                    
                    model.removeRow(locatedRow);
                    model.insertRow(locatedRow, new Object[]{imageLabel,code, name, descri, amt, qty});
                    JOptionPane.showMessageDialog(null, "Entry successfully edited!");
                    //clear fields after inserting the data
                    clearFields();
                    isInEditMode = false;
                    close();
                    pnlInventoryListForm.setVisible(true);
                    
                }
            }
        } else {
//            JOptionPane.showMessageDialog(null, "All Fields are filled");
            //Adding entered data to jtable
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty");
            
        }
}
catch(NullPointerException e)
{
    JOptionPane.showMessageDialog(null, "Please choose an image for the item before saving");
}
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed
    
    private void clearFields()
    {
        txtCode.setText("");
        txtName.setText("");
        txtDescription.setText("");
        txtAmount.setText("");
        txtQuantity.setText("");
        lblPictureHolder.setIcon(null);
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        popUpWarningLowOnStock();
    }//GEN-LAST:event_formWindowOpened
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        close();
        pnlInventoryEntryForm.setVisible(true);
        isInEditMode = true;
        //get image
        /*
        ImageIcon image = (ImageIcon)tblInventory.getValueAt(locatedRow, 0);
        Image image2 = image.getImage().getScaledInstance(lblPictureHolder.getWidth(), lblPictureHolder.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image3 = new ImageIcon(image2);
        lblPictureHolder.setIcon(image3);
        */
        
        //others
        txtCode.setText((String)tblInventory.getValueAt(locatedRow,1));
        txtName.setText((String)tblInventory.getValueAt(locatedRow,2));
        txtDescription.setText((String)tblInventory.getValueAt(locatedRow,3));
        txtAmount.setText((String)tblInventory.getValueAt(locatedRow,4));
        txtQuantity.setText((String)tblInventory.getValueAt(locatedRow,5));
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String Exit[]={"Yes","No"};
            int pili= JOptionPane.showOptionDialog(null,"Are you sure you want to delete this item?", "Delete", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE,null, Exit, Exit[1]);
        if(pili==0)
        {
            removeSelectedRows(tblInventory);
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeKeyPressed

    private void txtCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyTyped
        char c = evt.getKeyChar();
        if ( !(Character.isDigit(c)) && !(c == evt.VK_BACK_SPACE) && !(c == evt.VK_DELETE) ){
        evt.consume();
        }
        if(txtCode.getText().length()  >=  6) {  
        evt.consume();
        }
    }//GEN-LAST:event_txtCodeKeyTyped

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        char c = evt.getKeyChar();
        if ( !(Character.isLetter(c)) && !(c == evt.VK_BACK_SPACE) && !(c == evt.VK_DELETE) && !(c == evt.VK_SPACE) ){
        evt.consume();
        }
        if(txtCode.getText().length()  >=  6) {  
        evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyTyped
        char c = evt.getKeyChar();
        if ( !(Character.isDigit(c)) && !(c == evt.VK_BACK_SPACE) && !(c == evt.VK_DELETE) && !(c == evt.VK_PERIOD) ){
        evt.consume();
        }
        if(txtCode.getText().length()  >=  6) {  
        evt.consume();
        }
    }//GEN-LAST:event_txtAmountKeyTyped
    
    private void filter(String query)
    {
           TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
           tblInventory.setRowSorter(tr);
           tr.setRowFilter(RowFilter.regexFilter("(?i)" + query));
           
    }
    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        char c = evt.getKeyChar();
        if ( !(Character.isDigit(c)) && !(c == evt.VK_BACK_SPACE) && !(c == evt.VK_DELETE) ){
        evt.consume();
        }
        if(txtCode.getText().length()  >=  6) {  
        evt.consume();
        }
    }//GEN-LAST:event_txtQuantityKeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        char c = evt.getKeyChar();
        if ( !(Character.isLetterOrDigit(c)) && !(c == evt.VK_BACK_SPACE) && !(c == evt.VK_DELETE) && !(c == evt.VK_PERIOD) ){
        evt.consume();
        }
        else
        {
        String query = txtSearch.getText().toLowerCase();
        filter(query);
        }
    }//GEN-LAST:event_txtSearchKeyReleased
    
    void popUpWarningLowOnStock()
    {
        ArrayList<Integer> numdata = new ArrayList<Integer>();
        ArrayList<String> itemName = new ArrayList<String>();
        
        for (int count = 0; count < model.getRowCount(); count++){
             numdata.add(Integer.parseInt(model.getValueAt(count, 5).toString()));
             
}
        
        for (int count = 0; count < numdata.size(); count++){
             if(numdata.get(count) <= 20)
             {
                 itemName.add(model.getValueAt(count, 2).toString());
                 
             }
             
}
        JOptionPane.showMessageDialog(null,"THE FOLLOWING ITEM(S) ARE LOW ON STOCK(S):\n" + itemName + "\n\nPlease refer to the following phone nos. for supply delivery:\n[BUNS]202-555-0164\n[CHEESE]202-555-0125\n[FLOUR]202-555-0176\n[KETCHUP]202-555-0109\n[OTHERS...]202-555-0164", "Low on Stock(s)",JOptionPane.WARNING_MESSAGE);
    }
    
    private void pnlMenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuMouseDragged
        int coorX = evt.getXOnScreen();
        int coorY = evt.getYOnScreen();
        this.setLocation(coorX - mousePX, coorY - mousePY);
        
    }//GEN-LAST:event_pnlMenuMouseDragged

    private void pnlMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuMousePressed
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_pnlMenuMousePressed

    private void pnlBGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBGMouseDragged
        int coorX = evt.getXOnScreen();
        int coorY = evt.getYOnScreen();
        this.setLocation(coorX - mousePX, coorY - mousePY);
    }//GEN-LAST:event_pnlBGMouseDragged

    private void pnlBGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBGMousePressed
        mousePX = evt.getX();
        mousePY = evt.getY();
    }//GEN-LAST:event_pnlBGMousePressed

    private void tblInventoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventoryMouseReleased
      
        locatedRow = tblInventory.rowAtPoint(evt.getPoint());
        locatedCol = tblInventory.columnAtPoint(evt.getPoint());
        if (locatedRow >= 0 && locatedCol >= 0) {
            if(!(tblInventory.getSelectedRowCount() > 1))
            {
                btnEdit.setEnabled(true);
            }
        else
        {
            btnEdit.setEnabled(false);
        }
            btnDelete.setEnabled(true);

        }
        else
        {
            btnEdit.setEnabled(false);
            btnDelete.setEnabled(false);
        }
    }//GEN-LAST:event_tblInventoryMouseReleased

    private void tblInventoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInventoryMousePressed
        if(!(tblInventory.getSelectedRowCount() > 1))
            {
                btnEdit.setEnabled(true);
            }
        else
        {
            btnEdit.setEnabled(false);
        }
    }//GEN-LAST:event_tblInventoryMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                

        try {
            
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnChooseFile;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSettings;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMenuLogo;
    private javax.swing.JLabel lblPictureHolder;
    private javax.swing.JPanel pnlBG;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlInventoryEntryForm;
    private javax.swing.JPanel pnlInventoryListForm;
    private javax.swing.JPanel pnlMainCardLayout;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlReports;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
